//Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

//SignUp
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//UpdateProfile

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

//Add Education
export const EDUCTAION_UPDATE_REQUEST = "EDUCTAION_UPDATE_REQUEST";
export const EDUCATION_UPDATE_SUCCESS = "EDUCATION_UPDATE_SUCCESS";
export const EDUCATION_UPDATE_FAIL = "EDUCATION_UPDATE_FAIL";

// Add Experience
export const EXPERIENCE_UPDATE_REQUEST = "EXPERIENCE_UPDATE_REQUEST";
export const EXPERIENCE_UPDATE_SUCCESS = "EXPERIENCE_UPDATE_SUCCESS";
export const EXPERIENCE_UPDATE_FAIL = " EXPERIENCE_UPDATE_FAIL";

//Add Formation
export const FORMATION_UPDATE_REQUEST = "FORMATION_UPDATE_REQUEST";
export const FORMATION_UPDATE_SUCCESS = "FORMATION_UPDATE_SUCCESS";
export const FORMATION_UPDATE_FAIL = " FORMATION_UPDATE_FAIL";

//Interactive TimeLine
export const INTERACTIVE_TIMELINE_REQUEST = "INTERACTIVE_TIMELINE_REQUEST";
export const INTERACTIVE_TIMELINE_SUCCESS = "INTERACTIVE_TIMELINE_SUCCESS";
export const INTERACTIVE_TIMELINE_FAIL = "INTERACTIVE_TIMELINE_FAIL";
// create Skilledger
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
